import React, {useState} from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, Brain, BriefcaseBusiness, Check, ChevronDown, Compass, FlaskConical, Globe2, Heart, Lightbulb, Menu, MessageCircle, Rocket, ShieldCheck, Sparkles, Target, Trophy, Users, X, Zap } from 'lucide-react';
import './styles.css';

const programs = [
  {n:'01', icon:Brain, title:'Integrated AI Tuition', sub:'Learn Smarter. Go Further.', desc:'A modern learning approach combining academic support with AI-assisted, personalized learning.', points:['AI-assisted personalized learning','Concept-based learning with AI tools','Doubt clearing & practice sessions','Exam preparation support','Advanced learning pathways'], tag:'AI ENABLED · PERSONALIZED · BETTER RESULTS'},
  {n:'02', icon:Compass, title:'Career Guidance', sub:'Explore. Plan. Achieve.', desc:'Help students understand possibilities early and build a clearer path toward future study and careers.', points:['Career awareness from early stages','Career assessment & exploration','Course & career option guidance','Personalized career roadmaps','College and course guidance'], tag:'RIGHT GUIDANCE · REAL OPPORTUNITIES'},
  {n:'03', icon:Target, title:'Aptitude & Talent Identification', sub:'Know Your Strengths.', desc:'Structured assessments that help reveal strengths, abilities, aptitude and personal learning profiles.', points:['Scientific assessments','Identify strengths, abilities & aptitude','Personality & thinking profiles','Guidance sessions based on results'], tag:'ASSESS · IDENTIFY · DEVELOP · GROW'},
  {n:'04', icon:Rocket, title:'Advanced Career Excellence', sub:'Go Beyond the Textbook.', desc:'Development experiences that complement academics with practical skills and future-ready exposure.', points:['Go beyond academics','Applied learning & practical exposure','Quiz & reasoning training','Research & academic writing','Competitive exam exposure'], tag:'GO DEEPER · GO FURTHER'},
  {n:'05', icon:Sparkles, title:'AI Skills', sub:'AI for a Smarter Tomorrow.', desc:'Build practical confidence with the tools and habits shaping learning, creativity and productivity.', points:['AI tools for learning & creativity','Prompting & productivity skills','Coding & no-code platforms','Digital tools for modern learning','AI-assisted problem solving'], tag:'LEARN · CREATE · EXPLORE · APPLY'},
  {n:'06', icon:Lightbulb, title:'Innovation & Research', sub:'Ideas for a Better Tomorrow.', desc:'Turn curiosity into projects through science, technology, local problem-solving and innovation.', points:['Science & technology projects','Robotics & AI','Local problem-solving','Student innovation expo','Research & project ideas'], tag:'IDEAS · CREATION · REAL IMPACT'},
  {n:'07', icon:Heart, title:'Mind · Body · Balance', sub:'A Healthy Mind Builds a Brighter Future.', desc:'Support for wellbeing, emotional skills, healthy routines and a balanced student life.', points:['Mental wellbeing sessions','Emotional intelligence','Time management','Stress management','Sports & recreation','Nature & outdoor activities'], tag:'BE HEALTHY · BE HAPPY · BE YOUR BEST'},
  {n:'08', icon:Users, title:'Talent & Leadership', sub:'Express. Create. Lead.', desc:'Spaces for students to discover interests, express themselves and develop leadership qualities.', points:['Art, music, writing & public speaking','Coding, photography & creative skills','Leadership training','Entrepreneurship skills','Student showcase opportunities'], tag:'EXPLORE · EXPRESS · LEAD'},
  {n:'09', icon:ShieldCheck, title:'Remedial Teaching Support', sub:'Because Every Learner Matters.', desc:'Focused academic support for students who need extra help, confidence and consistent progress tracking.', points:['Personalized support for learning gaps','Small group & one-to-one sessions','Concept reinforcement and practice','Continuous assessment & progress tracking','Support to help students reach extra help'], tag:'SUPPORT · STRENGTHEN · PROGRESS'}
];

const events = [
 ['Young Scientist Challenge',FlaskConical],['Coding Challenge',Zap],['Young Speaker',MessageCircle],['Reading Mission',Compass],['Young Entrepreneur',BriefcaseBusiness],['Sports Programmes',Trophy],['Field Visit Experiences',Globe2],['Talent Showcase',Sparkles],['Expert Interaction with Professionals',Users],['Global Classroom',Globe2],['Community Projects',Heart],['AI Skills Workshops',Brain]
];
const fest = [['Innovation Expo',Lightbulb],['Career Fair',BriefcaseBusiness],['Student Talks',MessageCircle],['Talent Performances',Sparkles],['Sports Finals',Trophy],['Field Visit Showcase',Globe2],['Awards & Felicitations',Trophy]];

function App(){
 const [open,setOpen]=useState(false); const [active,setActive]=useState(null); const [sent,setSent]=useState(false);
 const scrollTo=(id)=>{setOpen(false);document.getElementById(id)?.scrollIntoView({behavior:'smooth'});};
 return <div className="site">
  <header className="nav"><div className="wrap navin"><a className="brand" href="#top" onClick={()=>scrollTo('top')}><div className="mark"><span></span><span></span><span></span></div><div><b>EDULLECTA</b><small>EDUCATION · SKILLS · OPPORTUNITIES</small></div></a><nav className={open?'open':''}><button onClick={()=>scrollTo('programs')}>Programs</button><button onClick={()=>scrollTo('events')}>Experiences</button><button onClick={()=>scrollTo('about')}>About</button><button className="navcta" onClick={()=>scrollTo('contact')}>Partner with us <ArrowRight size={16}/></button></nav><button className="menub" onClick={()=>setOpen(!open)} aria-label="menu">{open?<X/>:<Menu/>}</button></div></header>

  <main id="top">
   <section className="hero"><div className="heroGlow"></div><div className="wrap heroGrid"><div className="heroCopy"><div className="eyebrow"><span className="dot"></span> STUDENT DEVELOPMENT INITIATIVE</div><h1>Learn.<br/><em>Explore.</em><br/>Grow.</h1><p className="lead">A comprehensive student development initiative helping young minds build stronger futures through learning, skills, guidance, wellbeing and real-world exposure.</p><div className="actions"><button className="primary" onClick={()=>scrollTo('programs')}>Explore programs <ArrowRight size={18}/></button><button className="secondary" onClick={()=>scrollTo('contact')}>Talk to Edullecta</button></div><div className="heroStats"><div><strong>09</strong><span>Core programmes</span></div><div><strong>12+</strong><span>Special experiences</span></div><div><strong>01</strong><span>Student-first mission</span></div></div></div><div className="heroVisual"><div className="arch"></div><img src="/assets/brochure.png" alt="Edullecta student development brochure"/><div className="floatCard"><Sparkles size={17}/><div><b>Every child has a unique potential.</b><span>Help discover it. Help develop it.</span></div></div></div></div></section>

   <section className="promise" id="about"><div className="wrap promiseGrid"><div><p className="kicker">ABOUT EDULLECTA</p><h2>Helping young minds become <span>brighter futures.</span></h2></div><div><p>Edullecta is a student development initiative committed to providing high-quality educational support, career guidance, skill development and global exposure. We work toward a stronger Kerala by creating opportunities for students to learn, explore, express and grow.</p><div className="quote">“Every child has a unique potential. Our mission is to help them discover it, develop it and use it to create a better future.”</div></div></div></section>

   <section className="programSection" id="programs"><div className="wrap"><div className="sectionHead"><div><p className="kicker">OUR CORE PROGRAMMES</p><h2>One ecosystem.<br/><span>Many ways to grow.</span></h2></div><p>Academic learning is only one part of a student's journey. Edullecta brings together learning, future skills, wellbeing, talent and opportunity.</p></div><div className="programGrid">{programs.map((p,i)=>{const I=p.icon; return <article className={'program '+(i===0?'featured':'')} key={p.n} onClick={()=>setActive(p)}><div className="programTop"><span className="num">{p.n}</span><div className="icon"><I size={21}/></div></div><h3>{p.title}</h3><h4>{p.sub}</h4><p>{p.desc}</p><ul>{p.points.slice(0,4).map(x=><li key={x}><Check size={14}/>{x}</li>)}</ul><div className="tag">{p.tag}</div><button className="learn">View programme <ArrowRight size={15}/></button></article>})}</div></div></section>

   <section className="experience" id="events"><div className="wrap"><div className="experienceHead"><div><p className="kicker">SPECIAL PROGRAMMES & EVENTS</p><h2>Learning should feel<br/><span>alive.</span></h2></div><p>Experiences designed to take students beyond routine classroom learning and into curiosity, creativity, collaboration and real-world exposure.</p></div><div className="eventGrid">{events.map(([name,I])=><div className="event" key={name}><div className="eventIcon"><I size={20}/></div><span>{name}</span></div>)}</div></div></section>

   <section className="fest"><div className="wrap festGrid"><div className="festCopy"><div className="eyebrow light"><span className="dot"></span> YEAR-END GRAND EVENT</div><h2>EDULLECTA<br/><span>FUTURE FEST</span></h2><p>A celebration of young minds for a brighter tomorrow — bringing together ideas, careers, student voices, talent, sports, field experiences and recognition.</p><button className="festBtn" onClick={()=>scrollTo('contact')}>Explore collaboration <ArrowRight size={17}/></button></div><div className="festItems">{fest.map(([name,I])=><div key={name}><I/><span>{name}</span></div>)}</div></div></section>

   <section className="pillars"><div className="wrap"><div className="sectionHead"><div><p className="kicker">THE EDULLECTA APPROACH</p><h2>Learn. Explore.<br/><span>Experience. Grow.</span></h2></div><p>Designed around the idea that students need more than marks: they need confidence, skills, exposure, direction and opportunities to express their potential.</p></div><div className="pillarGrid"><div><Globe2/><b>Global Exposure</b><span>Broaden horizons through new experiences and perspectives.</span></div><div><Heart/><b>Confident Students</b><span>Build confidence, emotional skills and a sense of belonging.</span></div><div><Sparkles/><b>Future Skills</b><span>Develop practical abilities for a changing world.</span></div><div><Trophy/><b>A Stronger Kerala</b><span>Nurture today's learners as tomorrow's leaders.</span></div></div></div></section>

   <section className="contact" id="contact"><div className="wrap contactGrid"><div><p className="kicker">LET'S BUILD A BRIGHTER FUTURE</p><h2>Bring Edullecta to your <span>students.</span></h2><p>Interested in partnering, hosting a programme, or learning more about the student development ecosystem? Send an enquiry and start the conversation.</p><div className="contactNote"><ShieldCheck size={20}/><span>No payment or commitment is taken through this form.</span></div></div><form onSubmit={e=>{e.preventDefault();setSent(true)}}>{sent?<div className="success"><Check size={34}/><h3>Thank you.</h3><p>Your enquiry has been captured in this demo. Connect the form to your preferred email/CRM before launch.</p><button type="button" className="secondary" onClick={()=>setSent(false)}>Send another</button></div>:<><label>Name<input required placeholder="Your name"/></label><label>School / Institution<input placeholder="Institution name"/></label><label>How can we help?<select defaultValue=""><option value="" disabled>Select an option</option><option>Student development programme</option><option>Career guidance</option><option>AI & future skills</option><option>Events / workshops</option><option>Partnership</option><option>Other</option></select></label><label>Message<textarea rows="4" placeholder="Tell us a little about what you are looking for..."></textarea></label><button className="primary" type="submit">Send enquiry <ArrowRight size={17}/></button></>}</form></div></section>
  </main>
  <footer><div className="wrap foot"><div className="brand"><div className="mark"><span></span><span></span><span></span></div><div><b>EDULLECTA</b><small>EDUCATION · SKILLS · OPPORTUNITIES</small></div></div><span>Together for a brighter Kerala.</span><span>Learn · Explore · Grow</span></div></footer>

  {active&&<div className="modalBack" onClick={()=>setActive(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setActive(null)}><X/></button><div className="modalIcon"><active.icon size={25}/></div><span className="modalNum">{active.n}</span><h3>{active.title}</h3><h4>{active.sub}</h4><p>{active.desc}</p><ul>{active.points.map(x=><li key={x}><Check size={15}/>{x}</li>)}</ul><button className="primary" onClick={()=>{setActive(null);scrollTo('contact')}}>Enquire about this programme <ArrowRight size={16}/></button></div></div>}
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
